### ISSUE TITLE
Instance with name 'tippy-1' already exist, please pick unique [tippyName]

### ISSUE THREAD

**Issue by harvanchik** [farengeyt451/ngx-tippy-wrapper#26]
**Describe the bug**
Errors when using binded tippy in an `*ngFor`.

**To Reproduce**
1. Use `[ngxTippy]` in an `*ngFor`.

**Screenshots**
![image](https://user-images.githubusercontent.com/66141166/138565784-1b43616d-4c59-4b35-83f9-5bbee3aa9319.png)
![image](https://user-images.githubusercontent.com/66141166/138565725-bdba0c00-dde0-4b16-80eb-244d0bd29cbf.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome

**Environment context**
 - Angular version: 12.2.8
 - TypeScript version: 4.3.5

**Additional context**
Just upgraded to 4.0.0, and this problem **just now** introduced itself.

**Comment by Kr0san89** [comment]
The same issue arises if you use the tooltip on angular cdkDrag Element. 
It is that worse that it breaks the drag behavior, i guess relying on a "name" alltogether is kinda error prone, not sure if you could replace it with some kind of reference to the original element. 
I assume the *ngfor error comes when it rerenders (maybe with a change in the list) and therefore finding duplicates. 
At least at drag & drop it looks that way.

**Comment by farengeyt451** [comment]
@Kr0san89 @harvanchik fixed in v.5.0.0. Also plan to fix in 4.0.2 version.
So test please and feel free to create new issue in case of this bug returns.

**Comment by harvanchik** [comment]
I know this is ages later, but I actually do still get this error in the latest version 6.
